### ISSUE TITLE
Calculating pan, tilt, and zoom values

### ISSUE THREAD

**Issue by jahongir7174** [zSeriesGuy/PTZController#1]
@zSeriesGuy 
Thanks for your good repo.
I am going to calculate pan, tilt, and zoom values based on bounding box (person with red box) coordinates as shown picture below.
Can you help me to solve the problem?
![1](https://github.com/zSeriesGuy/PTZController/assets/71679734/28e402c7-ae1c-4f1c-a095-437c31112e9f)

**Comment by zSeriesGuy** [comment]
Cool. I have been thinking about doing something like that.
It has been a long time since I looked at coding. So this is just a guess.
For pan/tilt, get center (purple dot) of window by getting window width and height and divide in half.
For red box, do the same thing by computing the center of the red box.
Subtract center of red box from center of window to get the movement amount.
You can then tell camera to move plus or minus for pan and tilt values.
I don't recall how this part works. But you will have to determine how much movement +/- 1 is to the computed values.

For zoom, it would probably be about the same way where you compute the difference between the top left of the window to the top left of the red box.

I am curious. How will you find and determine the red box?

**Comment by jahongir7174** [comment]
@zSeriesGuy 
Thanks for your reply and good explanation.
The red can be obtained from a person tracker.
I found [one concept](https://stackoverflow.com/questions/44253787/translating-screen-coordinates-x-y-to-camera-pan-and-tilt-angles/71886256#71886256) from StackOverflow but I could not fit the concept to the ONVIF.
Can you help me to solve the problem?
